lib/subscribem/config/routes.rb
require "subscribem/constraints/subdomain_required"

Subscribem::Engine.routes.draw do
  constraints(Subscribem::Constraints::SubdomainRequired) do
    scope :module => "account" do
      root :to => "dashboard#index", :as => :account_root
      get "/sign_in", :to => "sessions#new", :as => :sign_in
      post "/sign_in", :to => "sessions#create", :as => :sessions
      get "/sign_up", :to => "users#new", :as => :user_sign_up
      post "/sign_up", :to => "users#create", :as => :do_user_sign_up
      get "/account", :to => "accounts#edit", :as => :edit_account
      patch "/account", :to => "accounts#update"
      get "/account/plan/:plan_id",
        :to => "accounts#plan",
        :as => :plan_account
      get "/account/subscribe",
        :to => "accounts#subscribe",
        :as => :subscribe_account
      post "/account/confirm_plan",
        :to => "accounts#confirm_plan",
        :as => :confirm_plan_account
    end
  end

  root "dashboard#index"
  get "/sign_up", :to => "accounts#new", :as => :sign_up
  post "/accounts", :to => "accounts#create", :as => :accounts


end

lib/subscribem/app/models/subscribem/account.rb
module Subscribem
  class Account < ActiveRecord::Base
    belongs_to :owner, :class_name => "Subscribem::User"
    accepts_nested_attributes_for :owner

    belongs_to :plan, :class_name => "Subscribem::Plan"

    validates :subdomain, :presence => true, :uniqueness => true
    validates :name, presence: true

    has_many :members, :class_name => "Subscribem::Member"
    has_many :users, :through => :members

    EXCLUDED_SUBDOMAINS = %w(admin)
    validates_exclusion_of :subdomain, :in => EXCLUDED_SUBDOMAINS, 
      :message => "is not allowed. Please choose another subdomain."

    validates_format_of :subdomain, :with => /\A[\w\-]+\Z/i,
                        :message => "is not allowed. Please choose another subdomain." 

    before_validation do
      self.subdomain = subdomain.to_s.downcase
    end

    def self.create_with_owner(params={})
      account = new(params)
      if account.save
        account.users << account.owner
      end
      account
    end

    def owner?(user)
      owner == user
    end
  end
end

lib/subscribem/app/controllers/subscribem/account/accounts_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class Account::AccountsController < ApplicationController
    before_filter :authenticate_user!
    before_filter :authorize_owner, only: [:edit, :update, :plan]

    def update
      plan_id = account_params.delete(:plan_id)
      if current_account.update_attributes(account_params)
        render status: :ok,
          json: {
              success: true, info: "Account updated successfully.", data: {
              account: current_account,
              subdomain: current_account.subdomain
            }
          }
        # flash[:success] = ""
        if plan_id != current_account.plan_id
          redirect_to plan_account_url(:plan_id => plan_id)
        else
          redirect_to root_path
        end
      else
        flash[:error] = "Account could not be updated."
        render :edit
      end
    end

    def plan
      @plan = Subscribem::Plan.find(params[:plan_id])
    end

    def subscribe
      @plan = Subscribem::Plan.find(params[:plan_id])
      @result = Braintree::TransparentRedirect.confirm(request.query_string)
      if @result.success?
        subscription_result = Braintree::Subscription.create(
          :payment_method_token => @result.customer.credit_cards[0].token,
          :plan_id => @plan.braintree_id
        )
        current_account.update_column(:plan_id, params[:plan_id])
        subscription_id = subscription_result.subscription.id
        current_account.update_column(:braintree_subscription_id, subscription_id)
        flash[:success] = "You have switched to the '#{plan.name}' plan."
        redirect_to root_path
      else
        flash[:error] = "Invalid credit card details. Please try again."
        render "plan"
      end
    end

    def confirm_plan
      @plan = Subscribem::Plan.find(params[:plan_id])
      subscription_id = current_account.braintree_subscription_id
      subscription_result = Braintree::Subscription.update(subscription_id,
        :plan_id => plan.braintree_id)

      if subscription_result.success?
        current_account.update_column(:plan_id, plan.id)
        flash[:success] = "You have switched to the '#{plan.name}' plan."
        redirect_to root_path
      else
        flash[:error] = "Something went wrong. Please try again."
        render "plan"
      end
    end

    private

    def account_params
      params.require(:account).permit(:name, :plan_id)
    end
  end
end

lib/subscribem/app/controllers/subscribem/account/dashboard_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class Account::DashboardController < ApplicationController
    before_filter :authenticate_user!
  end
end

lib/subscribem/app/controllers/subscribem/account/sessions_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class Account::SessionsController < Subscribem::ApplicationController
    def new
      @user = User.new
    end

    def create
      if env["warden"].authenticate(:scope => :user)
        render status: :ok,
          json: {
              success: true, info: "You are now signed in.", data: {
              user: @user,
            }
          }
#         flash[:success] = "You are now signed in."
#         redirect_to root_path
      else
        render status: :unprocessable_entity, json: { success: false, info: "Invalid email or password.", data: { } }
#         @user = User.new
#         flash[:error] = "Invalid email or password."
#         render :action => "new"
      end
    end
  end
end

lib/subscribem/app/controllers/subscribem/account/users_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class Account::UsersController < ApplicationController
    def new
      @user = Subscribem::User.new
    end

    def create
      account = Subscribem::Account.find_by(:subdomain => request.subdomain)
      user = account.users.create(user_params)
      force_authentication!(user)
      render status: :ok,
          json: {
              success: true, info: "You have signed up successfully.", data: {
              user: user,
            }
          }
#       flash[:success] = "You have signed up successfully."
#       redirect_to root_path
    end

    private
      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
  end
end

lib/subscribem/app/controllers/subscribem/accounts_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class AccountsController < ApplicationController
    def new
      @account = Subscribem::Account.new
      @account.build_owner
    end

    def create
      @account = Subscribem::Account.create_with_owner(account_params)
      if @account.valid?
        force_authentication!(@account.owner)
        render status: :ok,
          json: {
              success: true, info: "Your account has been successfully created.", data: {
              account: @account,
              subdomain: @account.subdomain
            }
          }
        # flash[:success] = ""
        # redirect_to subscribem.root_url(:subdomain => @account.subdomain)
      # else
      #   flash[:error] = "Sorry, your account could not be created."
        # render :new
      end
    end

    private

    def account_params
      params.require(:account).permit(:name, :subdomain, 
        { :owner_attributes => [
          [:email, :password, :password_confirmation]
        ]}
      )
    end
  end
end

lib/subscribem/app/helpers/subscribem/account/accounts_helper.rb
module Subscribem
  module Account::AccountsHelper
  end
end

lib/subscribem/app/helpers/subscribem/account/dashboard_helper.rb
module Subscribem
  module Account::DashboardHelper
  end
end

lib/subscribem/app/helpers/subscribem/account/sessions_helper.rb
module Subscribem
  module Account::SessionsHelper
  end
end

lib/subscribem/app/helpers/subscribem/account/users_helper.rb
module Subscribem
  module Account::UsersHelper
  end
end

lib/subscribem/app/helpers/subscribem/accounts_helper.rb
module Subscribem
  module AccountsHelper
  end
end

lib/subscribem/app/views/subscribem/account/accounts/_existing_subscription.html.erb
<%= form_tag confirm_plan_account_path(:plan_id => params[:plan_id]) do %>
  <%= submit_tag "Change plan" %>
<% end %>

lib/subscribem/app/views/subscribem/account/accounts/_new_subscription.html.erb
<% if @result && @result.message %>
  <ul class="gateway_messages">
    <% @result.message.split("\n").each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for :customer,
     :url => Braintree::TransparentRedirect.url,
     :html => {:autocomplete => "off"} do |customer| -%>
  <% tr_data = Braintree::TransparentRedirect.create_customer_data(
     :redirect_url => subscribem.subscribe_account_url(:plan_id => params[:plan_id]),
   ) %>
  <%= hidden_field_tag "tr_data", tr_data %>
  <%= customer.fields_for :credit_card do |cc| -%>
    <p>
      <%= cc.label :number, "Credit card number" %><br>
      <%= cc.text_field :number %>
    </p>

    <p>
      <%= cc.label :cardholder_name, "Name on card" %><br>
      <%= cc.text_field :cardholder_name %>
    </p>

    <p>
      <%= cc.label :expiration_date, "Expiration date" %><br>
      <%= cc.text_field :expiration_date %>
    </p>

    <p>
      <%= cc.label :cvv, "CVV" %><br>
      <%= cc.text_field :cvv %>
    </p>
    <%= customer.submit "Change plan" %>
  <% end %>

<% end %>

lib/subscribem/app/views/subscribem/account/accounts/edit.html.erb
<h2>Edit Account</h2>

<%= form_for(current_account, :url => account_path) do |account| %>
  <%= account.error_messages %>
  <p>
    <%= account.label :name %>
    <%= account.text_field :name %>
  </p>

  <p>
    <%= account.label :plan_id %>
    <% plans = Subscribem::Plan.all.map { |p| [p.name, p.id] } %>
    <%= account.select :plan_id, plans %>
  </p>

  <%= account.submit "Update Account" %>
<% end %>

lib/subscribem/app/views/subscribem/account/accounts/plan.html.erb
<div class='plan-info'>
  <p>
    You are changing to the '<%= @plan.name %>' plan.
  </p>

  <p>
    This plan costs <strong>$<%= @plan.price %></strong> per month.
  </p>
</div>

<% if current_account.braintree_subscription_id.present? %>
  <%= render "existing_subscription" %>
<% else %>
  <%= render "new_subscription" %>
<% end %>